# Local storage

# What do we want? 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Here we are asking for 20gb, and for this we will need to find a volume with at least 20gb
      storage: 20Gi

---

# How do we want it implemented?
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    # This is physical storage, e.g. in EBS it will allocate a 20Gi disk
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/feeltman/location/mongodata"
    type: DirectoryOrCreate
