# Local storage

# What do we want? 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongo-pvc
spec:
  storageClassName: cloud-ssd
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Here we are asking for 20gb, and for this we will need to find a volume with at least 20gb
      storage: 7Gi

---

# How do we want it implemented?
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
